### ISSUE TITLE
Local image is not working

### ISSUE THREAD

**Issue by rbecharast-chwy** [max-prokopenko/react-native-gif#5] opened 2021-06-07 23:42 UTC
Hi, I added an local image but the component does not render it.
`  <GifImage
          source={localImage}
          style={{
            width: 100,
            height: 100,
          }}
        />`

 - Device: iPhone 12
 - OS: 14.5
 - React Native 0.64.2
 - React: 17.0.1

**Comment by max-prokopenko** [comment] 2021-06-08 07:15
Hi, there indeed was a bug with local GIFs. Now it should be fixed in v2.2.1 with #6 . Please let me know if the issue is still there!

**Closed as completed by max-prokopenko** 2021-06-08 07:15 UTC
Labels: bug
